### ISSUE TITLE
[Enhancement] Auto login

### ISSUE THREAD

**Issue by nicomazz** [sommoMicc/Uniweb-Skin#1]
Proporrei un'opzione per far in modo che, accedendo alla home di uniweb, si venga reindirizzati automaticamente alla pagina di login (riducendo di un click il 99% degli accessi)

**Comment by sommoMicc** [comment]
Ci sta, provo a vedere cosa si riesce a fare.
Magari si potrebbe fare un controllo sugli elementi del menu e vedere se c'è l'opzione di login, e in tal caso cliccarla

**Comment by sommoMicc** [comment]
Aggiunto in #https://github.com/sommoMicc/Uniweb-Skin/commit/ed05e84740fe5842bb1f200ff6d925d87740654c

**Comment by sommoMicc** [comment]
Aggiunto in https://github.com/sommoMicc/Uniweb-Skin/commit/ed05e84740fe5842bb1f200ff6d925d87740654c
